### ISSUE TITLE
Support modeling forall-like functions

### ISSUE THREAD

**Issue by jxv** [cjdev/test-fixture#1]
For example, I wish to model these functions under a `TestFixture`:
[`exitFailure :: IO a`](https://hackage.haskell.org/package/base-4.9.0.0/docs/System-Exit.html)
[`timeIt :: IO a -> IO a`](https://hackage.haskell.org/package/timeit-1.0.0.0/docs/System-TimeIt.html)

**Comment by lexi-lambda** [comment]
Can you give an example where you need to handle this kind of function, but this package currently cannot support it?
