### ISSUE TITLE
Type aliases for common patterns?

### ISSUE THREAD

**Issue by lexi-lambda** [cjdev/test-fixture#11]
It is very frequent to have type signatures that look like one of the following:

- `Monad m => Fixture m` (not using writer or state)
- `Fixture (TestFixture Fixture [Something] ())` (only using writer)

Would it make sense to provide type aliases for these cases, especially when paired with `mkFixture`? What could they be called?

**Comment by jxv** [comment]
Some suggestions:
```haskell
type Fixture' = Fixture (TestFixture Fixture () ())
type FixtureW w = Fixture (TestFixture Fixture w ())
type FixtureS s = Fixture (TestFixture Fixture () s)
type FixtureWS w s = Fixture (TestFixture Fixture w s)
```
