### ISSUE TITLE
Always a list for log/writer

### ISSUE THREAD

**Issue by jxv** [cjdev/test-fixture#14]
This isn't an issue; it's a discussion point.
Do we have or know of any use cases where shouldn't use a list? This is ignoring the tuple/unit situation when the `w` isn't used.

**Comment by jxv** [comment]
A pro for "always use list" is that a truly deterministic test would imply a certain order of `tell` calls.

**Comment by lexi-lambda** [comment]
I like this idea. I think it’s inline with the goal of making this library more specialized for the purposes of testing and moving away from a thin wrapper around RWST. 👍 from me.
