### ISSUE TITLE
Support for stubbing out polymorphic functions with monomorphic implementations

### ISSUE THREAD

**Issue by lexi-lambda** [cjdev/test-fixture#19]
This is a pretty complicated idea, but unfortunately, it’s something I imagine being relatively common desire. Basically, imagine having a generic `DB` typeclass:

``` haskell
class Monad m => DB m where
  get :: RelationalEntity record => Key record -> m (Maybe record)
  insertBy :: RelationalEntity record => record -> m (Either (Entity record) (Key record))
  selectList :: RelationalEntity record => m [Entity record]
  delete :: RelationalEntity record => Key record -> m ()
```

Note that each of these functions is _polymorphic_ on its return type. This is a really useful property to have, but it’s nearly impossible to test with test-fixture. To illustrate, consider a function that implements a `GET /users` endpoint, which looks something like this:

``` haskell
getUsers :: DB m => m [Entity User]
getUsers = do
  users <- selectList
  return $ filter isActive users
```

Now, someone might want to test the above function with test-fixture by stubbing out `selectList` to return a list of both active and inactive users. They might write something like this:

``` haskell
let fixture = def { _selectList = return [activeUser, inactiveUser] }
unTestFixture getUsers fixture `shouldBe` [activeUser]
```

This does not typecheck, however, because the type of `_selectList` _must be polymorphic on its return type_, but the above implementation is monomorphic over users. I’m not sure how to solve this, but it’s a feature we really need to support.

**Comment by jxv** [comment]
I think we can solve this using the `ExistentialQuantification` extensions such that the generated fixture will look something like this:
```haskell
data Fixture m = forall record. RelationalEntity record => Fixture
  { _get :: Key record -> m (Maybe record)
  , _insertBy :: record -> m (Either (Entity record) (Key record))
  , _selectList :: m [Entity record]
  , _delete :: Key record -> m ()
  }
```

**Comment by mitchellwrosen** [comment]
@jxv This idea doesn't quite work since you couldn't update `def` in any way, e.g. record update syntax. Like, this wouldn't compile:

```haskell
let fixture = def { _selectList = return [activeUser, inactiveUser] }
```

You'd have to define it all at once:

```haskell
let fixture = Fixture { _get = undefined, _insertBy = undefined, _selectList = ..., _delete = undefined }
```

Painful =(

**Comment by mitchellwrosen** [comment]
The record type could paramaterize the fixture:

```haskell
data Fixture record m = Fixture
  { _get :: Key record -> m (Maybe record)
  , _insertBy :: record -> m (Either (Entity record) (Key record))
  , _selectList :: m [Entity record]
  , _delete :: Key record -> m ()
  }

instance RelationalEntity record => DB (Fixture record) where
  ...
```

**Comment by lexi-lambda** [comment]
I don’t think either of those would work, right? The types of the methods of `DB` are quantified such that the *caller* is allows to choose what `record` is, and the implementations will never be allowed to pick themselves.

A workaround I’ve discovered is to use `Data.Dynamic` and add a `Typeable` constraint to `RelationalEntity`, which makes it possible to cheat a little in the tests. It’s actually not as verbose as I expected it to be, but it’s still a little icky. It might be possible to provide some facilities to make working with `Typeable` nicer, but it would be better if we could come up with something that would avoid it entirely.

**Comment by mitchellwrosen** [comment]
Ah yes, what I said doesn't work at all! Apologies

**Comment by lexi-lambda** [comment]
Here is an example of a module that uses `Data.Typeable` and `Data.Type.Equality` to provide helper functions for creating monomorphic implementations of polymorphic functions:

```haskell
{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE TypeApplications #-}

module PartialMonomorphic
  ( assertEq
  , withAssertEq
  , withAssertEq_
  , (:~:)(..)
  ) where

import Data.Maybe (fromMaybe)
import Data.Monoid ((<>))
import Data.Proxy (Proxy(..))
import Data.Typeable (Typeable, (:~:)(Refl), eqT, typeRep)
import Data.Type.Equality (gcastWith)

assertEq :: forall a b. (Show a, Typeable a, Typeable b) => a -> (a :~: b)
assertEq x = fromMaybe (error errorMessage) eqT
  where errorMessage =
            "expected value of type ‘" <> show (typeRep (Proxy :: Proxy b))
         <> "’, but got ‘" <> show x
         <> "’, which is of type ‘" <> show (typeRep (Proxy :: Proxy a)) <> "’"

withAssertEq :: forall b a c. (Show a, Typeable a, Typeable b) => a -> ((a ~ b) => b -> c) -> c
withAssertEq x f = withAssertEq_ @b x (f x)

withAssertEq_ :: forall b a c. (Show a, Typeable a, Typeable b) => a -> ((a ~ b) => c) -> c
withAssertEq_ x = gcastWith (assertEq x :: (a :~: b))
```

I have used these helpers a little, and they seem to work decently, but they are sort of complicated. I am not sure if they are good or straightforward enough to include in `test-fixture`.

**Comment by jxv** [comment]
@lexi-lambda Can you these guys, at least in a branch?
```haskell
assertEq
withAssertEq
assertEqT
withAssertEqT
(:~:)(..)
```

**Comment by lexi-lambda** [comment]
I’ve pushed them to the branch [type-equality](/cjdev/test-fixture/tree/type-equality).

**Comment by lexi-lambda** [comment]
Closing because this issue is now solved by the [type-assertions](https://github.com/lexi-lambda/type-assertions) package.
