### ISSUE TITLE
Generating instances for partially-applied multi-parameter typeclasses with fundeps

### ISSUE THREAD

**Issue by berdario** [cjdev/test-fixture#25]
I mentioned this in the [other issue](https://github.com/cjdev/test-fixture/issues/24#issuecomment-254662386)... Unfortunately I haven't had time to properly dig into this, but at least here's a minimal project example, using the same dependency that I was using:

https://github.com/berdario/test-fixture/tree/monadlog-failure

This is the error you'll get when trying to build it:

    mkDictInstanceFunc: expected method signature, given DefaultSigD Control.Monad.Log.logMessageFree (ForallT [KindedTV message_1627435475 StarT,KindedTV m_1627435476 (AppT (AppT ArrowT StarT) StarT)] [AppT (AppT (ConT Control.Monad.Log.MonadLog) (VarT message_1627435475)) (VarT m_1627435476)] (ForallT [KindedTV t_1627435477 (AppT (AppT ArrowT (AppT (AppT ArrowT StarT) StarT)) (AppT (AppT ArrowT StarT) StarT)),KindedTV n_1627435478 (AppT (AppT ArrowT StarT) StarT)] [AppT (AppT EqualityT (VarT m_1627435476)) (AppT (VarT t_1627435477) (VarT n_1627435478)),AppT (ConT Control.Monad.Trans.Class.MonadTrans) (VarT t_1627435477),AppT (AppT (ConT Control.Monad.Log.MonadLog) (VarT message_1627435475)) (VarT n_1627435478)] (AppT (AppT ArrowT (ForallT [KindedTV mon_1627435483 StarT] [AppT (ConT GHC.Base.Monoid) (VarT mon_1627435483)] (AppT (AppT ArrowT (AppT (AppT ArrowT (VarT message_1627435475)) (VarT mon_1627435483))) (VarT mon_1627435483)))) (AppT (VarT m_1627435476) (TupleT 0)))))

I suspect that the error might be caused by the fact that MonadLog relies on functional dependencies?

I worked around it in my small project by doing:

    import           Control.Monad.Log          (LoggingT (..), WithSeverity,
                                                 runLoggingT)
    import qualified Control.Monad.Log          as Log
    
    class (Monad m) => Log m where
         logDebug :: Text -> m ()
         logInfo :: Text -> m()
    
    instance (Monad m) => Log (LoggingT (WithSeverity Text) m) where
        logDebug = Log.logDebug
        logInfo = Log.logInfo

**Comment by lexi-lambda** [comment]
Yeah, `MonadLog` is a multi-parameter typeclass, so it’s not technically supported. Maybe it could/should be, though, since it uses functional dependencies? It seems like maybe you should be able to write something like this:

```haskell
mkFixture "Fixture" [ [t|MonadLog Text|] ]
```

That is, each argument must be a single-parameter, monadic constraint, but the constraint itself might be a partially-applied typeclass.

Anyway, the error message is at least better on `master`, so we should release a `0.4.1.1` to make it clearer what’s going on here.
