### ISSUE TITLE
Remove the state parameter from fixture functions that do not return state

### ISSUE THREAD

**Issue by lexi-lambda** [cjdev/test-fixture#8]
Given that state is so infrequently used as it is, and given that it’s very easy to ignore unused return values, I think the state argument should be removed from `unTestFixture` and `logTestFixture`, so their type signatures should be as follows:

```haskell
unTestFixture :: TestFixture r () () a -> r (WS () ()) -> a
logTestFixture :: TestFixture r w () a -> r (WS w ()) -> w
```

With some nice type aliases (maybe making `TestFixture` an opaque newtype instead of a type alias) I think this would make the API a lot less confusing than it currently is.

**Comment by jxv** [comment]
+1 for newtypes

+1 for removing unit `()`
